[[redirects]]
  from = "https://www.tuerex.at/*"
  to = "https://tuerex.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tuerex.at/echtsverbindliche.pdf"
  to = "https://tuerex.at/rechtsverbindliche.pdf"
  status = 301
  force = true


[[redirects]]
  from = "https://super-puffpuff-f8ff31.netlify.app/*"
  to = "https://tuerex.at/:splat"
  status = 301
  force = true
